### ISSUE TITLE
Allow annotating library functions with @NonNls

### ISSUE THREAD

**Issue by phiresky** [hpoul/string_literal_finder#1]
Thanks for this plugin, it's great!

There's a ton of false positives though that seem like they should be somewhat easily prevented:

e.g.:

* developer.log('foobar'); // don't want to translate debug messages
* json["key"] // you'd probably almost never want to translate the keys of a Map<String, ...>
* Image.asset("assets/foo/bar") // library function that takes a file path

It would be great if there was a way to whitelist library functions that you don't control, e.g. in the config file. I'm imagining something like this:

```yaml
string_literal_finder:
   non-nls:
      - "dart:core:Map[]" # [] operator on map
      - "dart:developer:log"
      - "package:flutter/src/widgets/image.dart:Image.asset"
```
